//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class stdcourse
    {
        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual course course { get; set; }
        public virtual student student { get; set; }
    }
}
